version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: zen-ci-app

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8081:8080"  
      - "50000:50000"  
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock 

volumes:
  jenkins_home:

